apiVersion: v2
name: armore
description: A Helm chart for Armore

type: application

# This is the chart version. This version number should be incremented each time you make changes
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

dependencies:
# If cert-manager is updated be sure to download new custom-resource-definitions
# Place the yaml in the crds/ directory
# Current version: https://github.com/jetstack/cert-manager/releases/download/v1.1.0/cert-manager.crds.yaml
- name: cert-manager
  version: "1.1.0"
  repository: "https://charts.jetstack.io"
  tags:
    - certManager
- name: ingress-nginx
  version: "3.19.0"
  repository: "https://kubernetes.github.io/ingress-nginx"
  tags:
    - nginx