{{- $fullName := include "armore.fullname" . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-config" $fullName }}
  labels:
    {{- include "armore.labels" . | nindent 4 }}
data:
  cloudProjectId: {{ .Values.cloud.projectId }}
  cloudStorageBucket: {{ .Values.cloud.pictureStorageBucket }}
  cloudStorageType: {{ .Values.cloud.pictureStorageType }}
  redisUrl: {{ printf "redis://%s-redis" $fullName }}
