{{- $fullName := include "armore.fullname" . }}
{{- $labels := include "armore.labels" . }}
{{- $globalContext := . }}
{{- range $path, $bytes := .Files.Glob "secrets/**.toml" }}
{{- $fileName := splitList "secrets/" $path | join "" }}
{{- $secretName := splitList ".toml" $fileName | join "" }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $fullName }}-{{ $secretName }}"
type: Opaque
data:
{{- range $globalContext.Files.Lines $path }}
  {{- $a := splitn "=" 2 . }}
  {{- if $a._0 }}
  {{- $a._0 | nindent 2 }}: {{ $a._1 }}
  {{- end }}
{{- end }}
---
{{- end }}