{{- $globalContext := . }}
{{- range .Values.deployments }}
{{- if .enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" (include "armore.fullname" $) .name | trunc 63 }}
  labels:
    {{- include "armore.labels" $ | nindent 4 }}
    app: {{ .name }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      {{- include "armore.selectorLabels" $ | nindent 6 }}
      app: {{ .name }}
  template:
    metadata:
      {{- with .podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "armore.selectorLabels" $ | nindent 8 }}
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: {{ printf "%s:%s" .image.repository .image.tag }}
          imagePullPolicy: {{ .image.pullPolicy }}
          {{- with .ports  }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .command }}
          command: {{ . }}
          {{- end }}
          {{- with .args }}
          args: {{ . }}
          {{- end }}
          resources:
            {{- toYaml .resources | nindent 12 }}
          {{- with .securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .lifecycle }}
          lifecycle:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
          {{- with .env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- range .dependencies }}
            {{- $func := printf "armore.%s" . }}
            {{- include $func $ | nindent 12 }}
          {{- end }}
          {{- if and .cloudSql $globalContext.Values.tags.cloudSql -}}
          {{- printf "volumeMounts:" | nindent 10 }}
            {{- include "armore.cloudSqlVolumeMount" $ | nindent 12 }}
        {{- include "armore.cloudSqlSidecar" $ | nindent 8 }}
          {{- end }}
      {{- if and .cloudSql $globalContext.Values.tags.cloudSql }}
      volumes:
        {{- include "armore.cloudSqlVolume" $ | nindent 8 }}
      {{- end }}
---
{{- end }}
{{- end }}
