{{- if .Values.ingress.enabled -}}
{{- $fullName := include "armore.fullname" . -}}
{{- $namespace := .Release.Namespace -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: "{{ $fullName }}-ingress"
  labels:
    {{- include "armore.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        {{- if eq $namespace "default"  }}
        - {{ . | quote }}
        {{- else }}
        {{- $host := splitn "." 2 . }}
        - {{ printf "%s.%s.%s" $host._0 $namespace $host._1 | quote }}
        {{- end }}
        {{- end }}
      secretName: {{ printf "%s-%s" $fullName .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    {{- if eq $namespace "default"  }}
    - host: {{ .host | quote }}
    {{- else }}
    {{- $host := splitn "." 2 .host }}
    - host: {{ printf "%s.%s.%s" $host._0 $namespace $host._1 | quote }}
    {{- end }}
      http:
        paths:
          {{- $serviceName := .name -}}
          {{- $servicePort := .servicePort -}}
          {{- range .paths }}
          - path: {{ . }}
            backend:
                serviceName: {{ printf "%s-%s" $fullName $serviceName }}
                servicePort: {{ $servicePort }}
          {{- end }}
    {{- end }}
  {{- end }}
