{{- $fullName := include "armore.fullname" . }}
{{- $labels := include "armore.labels" . }}
{{- $globalContext := . }}
{{- range .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $fullName }}-{{ .name }}"
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
{{- range $key, $value := .data }}
  {{- printf "%s: %s" $key ($value | b64enc) | nindent 2 }}
{{- end }}
{{- range $key, $value := .base64Data }}
  {{- printf "%s: %s" $key ($value) | nindent 2 }}
{{- end }}
---
{{- end }}