{{- $fullName := include "armore.fullname" . }}
{{- $labels := include "armore.labels" . }}
{{- $selectorLabels := include "armore.selectorLabels" . }}
{{- range .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" $fullName .name | trunc 63 }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  type: NodePort
  ports:
    {{- toYaml .ports | nindent 4 }}
  selector:
    {{- $selectorLabels | nindent 4 }}
    app: {{ .name }}
---
{{- end }}