apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-controller
  namespace: default
data:
  # Armore custom config
  limit-connections: "20"
  limit-rpm: "120"
  log-format-upstream: $remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent $http_referer [$http_platform, $http_build, $http_model] \"$http_user_agent\" $request_length $request_time [$proxy_upstream_name] [$proxy_alternative_upstream_name] $upstream_addr $upstream_response_length $upstream_response_time $upstream_status $req_id
  proxy-body-size: 8m
  proxy-connect-timeout: "60"
  proxy-next-upstream-timeout: "60"
  proxy-read-timeout: "60"
  proxy-send-timeout: "60"
