FROM nginx:alpine
#COPY build/unbundled /usr/share/nginx/html
#RUN cat /etc/nginx/nginx.conf
#RUN cat /etc/nginx/conf.d/default.conf
#COPY nginx/default.conf /etc/nginx/conf.d/default.conf
#COPY nginx/nginx.conf /etc/nginx/nginx.conf
