FROM rust:1.42.0

WORKDIR /app

COPY . .
RUN rustup default nightly-2020-05-18
# Build cargo cache
RUN cargo build

RUN rustup default nightly-2020-05-18

# Install DB Migration tool.
RUN ["curl", "-fsSL", "-o", "/usr/local/bin/dbmate", "https://github.com/amacneil/dbmate/releases/download/v1.10.0/dbmate-linux-amd64"]
RUN ["chmod", "+x", "/usr/local/bin/dbmate"]

STOPSIGNAL SIGINT
